services:
  browser-use-api:
    image: chaoszhu/browser-use-api:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./browser-use-api/media:/app/media
      - ./browser-use-api/data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s